### ISSUE TITLE
Sobre Account information

### ISSUE THREAD

**Issue by davirs** [dholidev/module-correios-frete#1]
Desculpe a ignorância, é que são tantos acessos diferentes dos correios que fiquei perdido.

Código ECT e Senha ECT são referentes a que? código de postagem, código administrativo, sigepweb... 
não encontrei nada a respeito na documentação do módulo..

Desde já agradeço!

**Comment by dholidev** [comment]
Olá davirs, tudo certo.

Perdoe-nos pela falta de clareza. Não é ignorância não, é que a gente está tão acostumado que esquece de esclarecer as coisas.

Código ECT: é seu convênio junto aos Correios.
Senha ECT: 8 primeiros dígitos do seu CNPJ.

Você irá encontrar dificuldades para conseguir as credenciais do SRO. Maioria dos Gerentes dos Correios quase não sabe o que é.

Abraço.

**Comment by davirs** [comment]
Top!!! obrigado
