### ISSUE TITLE
Dúvida sobre códigos dos correios.

### ISSUE THREAD

**Issue by davirs** [dholidev/module-correios-frete#2]
Olá! O módulo funciona muito bem!
Só tenho uma dúvida com relação aos códigos dos correios que trocam toda hora...

No meu caso os códigos são 3085 e 3050. É possível inserir isso no módulo de alguma forma?

![image](https://user-images.githubusercontent.com/4355062/102723709-a996a480-42e8-11eb-9576-2aab8c13c6c8.png)

![image](https://user-images.githubusercontent.com/4355062/102723821-a6e87f00-42e9-11eb-8a0d-ddfc83104542.png)

**Comment by dholidev** [comment]
Olá davirs, tudo bem?

Você poderá inserir os códigos na sua instalação Magento 2, pasta vendor/dholi/module-correios-frete/src/module-correios-frete/Model/Carrier.php

1 - na linha 77, mude:

de: protected $reverse = ['4510' => '04510', '4669' => '04669', '4014' => '04014', '4162' => '04162'];
para: protected $reverse = ['4510' => '04510', '4669' => '04669', '4014' => '04014', '4162' => '04162'**, 3050 => '03050', 3085' => '03085'**];

* em alguns serviços os Correios exigem que seja enviado o código sem o ZERO, mas é retornado com o ZERO.

2 - na linha 219, adicione mais uma entrada no array

'**3050**' => '3050 - Nome do serviço que aparecerá no ADMIN'

3 - na linha 229, adicione mais uma entrada no array

'**3050**' => '3050 - Nome do serviço que aparecerá para o CLIENTE'

Abraço.

**Comment by dholidev** [comment]
Olá davirs,

tivemos de incluir os serviços 03050 e 03085.

Pode atualizar para a nova versão rodando: composer require dholi/module-correios-frete:1.0.1

Abraço.
